version: "2"
run:
  concurrency: 1
  go: 1.24.0
  allow-parallel-runners: false
  allow-serial-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    goconst:
      match-constant: false
      min-len: 5
      min-occurrences: 10
    gocyclo:
      min-complexity: 50
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: early-return
          disabled: true
        - name: enforce-map-style
          disabled: true
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: get-return
          disabled: true
        - name: if-return
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: optimize-operands-order
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: use-any
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: deep-exit
          disabled: true
        - name: superfluous-else
          disabled: true
        - name: confusing-results
          disabled: true
        - name: defer
          disabled: true
        - name: var-naming
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: struct-tag
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: error-strings
          disabled: true
        - name: max-control-nesting
          arguments:
            - 6
    staticcheck:
      checks:
        - -ST1000
        - -ST1003
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - .*\.zz_generated\..*
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - .*\.zz_generated\..*
      - third_party$
      - builtin$
      - examples$
