# .goreleaser.yaml
# Configuration for GoReleaser
# See https://goreleaser.com for more information

version: 2

project_name: reproxy

before:
  hooks:
    - go mod tidy
    - gofmt -s -w .

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Tag}}
      - -X main.buildDate={{.Date}}
    binary: reproxy

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: letronghoangminh
    name: reproxy
  prerelease: auto
  draft: false
  name_template: "Reproxy {{.Tag}}"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    package_name: reproxy
    maintainer: Le Trong Hoang Minh <letronghoangminh@gmail.com>
    description: A highly configurable reverse proxy server with load balancing
    homepage: https://github.com/letronghoangminh/reproxy
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: config/config.yaml
        dst: /etc/reproxy/config.yaml
        type: config
      - src: README.md
        dst: /usr/share/doc/reproxy/README.md

env:
  - GO111MODULE=on
