# .goreleaser.yaml
# Configuration for GoReleaser
# See https://goreleaser.com for more information

project_name: reproxy

before:
  hooks:
    - go mod tidy
    - gofmt -s -w .

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go
    ldflags:
      - -s -w
      - -X main.buildVersion={{.Tag}}
      - -X main.buildDate={{.Date}}
    binary: reproxy

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - config/config.yaml

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: letronghoangminh
    name: reproxy
  prerelease: auto
  draft: false
  name_template: "Reproxy {{.Tag}}"

dockers:
  - image_templates:
      - "letronghoangminh/reproxy:latest"
      - "letronghoangminh/reproxy:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
      - config/config.yaml

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    package_name: reproxy
    maintainer: Le Trong Hoang Minh <letronghoangminh@gmail.com>
    description: A highly configurable reverse proxy server with load balancing
    homepage: https://github.com/letronghoangminh/reproxy
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: config/config.yaml
        dst: /etc/reproxy/config.yaml
        type: config
      - src: README.md
        dst: /usr/share/doc/reproxy/README.md

env:
  - GO111MODULE=on
