listeners:
  - host: ["localhost:2211"]
    handlers:
      - matchers:
          path: "/static"
        static_response:
          status: 200
          body: "Hello, World!"

      - matchers:
          path: "/files"
        static_files:
          root: "/Users/hoangminh/Code/reproxy"

  - host: ["psycholog1st.local:2210"]
    handlers:
      - matchers:
          path: "/reverse"
          method: ["GET", "POST", "*"]
          headers:
            X-Test-Header1: test
          client_cidrs: ["1.2.3.4/32", "0.0.0.0/0", "::/0"]
          query:
            test: "test"
        reverse_proxy:
          rewrite: "/rewrite/{path}"
          upstreams: 
            static: ["http://localhost:8081", "http://localhost:8082", "http://localhost:8083"]
            dynamic:
              - type: A
                value: "http://example.com:8080"
          load_balancing:
            strategy: sticky
            retries: 5
            try_interval: 10
          add_headers:
            X-Real-IP: "{remote_ip}"
          remove_headers:
            - "X-Test-Header1"
            - "X-Test-Header2"

global:
  port: 2209
  log_level: info
