listeners:
  - host: ["localhost:2211"]
    handlers:
      - path: "/static"
        static_response:
          status: 200
          body: "Hello, World!"

      - path: "/files"
        static_files:
          root: "/Users/hoangminh/Code/reproxy"
          index_files: ["index.html"]

  - host: ["psycholog1st.local:2210"]
    handlers:
      - path: "/reverse"
        reverse_proxy:
          upstreams: ["http://localhost:8081", "http://localhost:8082", "http://localhost:8083"]
          load_balancing:
            strategy: round_robin
            retries: 3
            try_interval: 30
          add_headers:
            X-Real-IP: "{remote_ip}"
          remove_headers:
            - "X-Test-Header1"
            - "X-Test-Header2"

global:
  port: 2209
  log_level: info
